import matplotlib.pyplot as plt                             # importing plotting functions 
import numpy as np

from data import Pc, Tc, gamma, R, At, Ae, Pa               # importing data and equations 
from nozzel import area_ratio, exit_temperature, exit_pressure, exit_velocity
from mnum import exit_mach
from engine import mass_flow_rate, thrust, isp

expansion_ratios = np.linspace(5, 100, 50)                  # expansion ratio values and steps used in equations 
isp_values = []                                             # isp values generated by the equations 

for eps in expansion_ratios:                                # loop to calculate the isp for all the expansion ratios
    Me = exit_mach(eps, gamma)
    Te = exit_temperature(Tc, gamma, Me)
    Pe = exit_pressure(Pc, Tc, Te, gamma)
    Ve = exit_velocity(gamma, R, Tc, Pe, Pc)
    mdot = mass_flow_rate(Pc, At, Tc, gamma, R)
    F = thrust(mdot, Ve, Pe, Pa, Ae)
    Isp = isp(F, mdot)
    isp_values.append(Isp)

plt.figure()                                                # plotting the data and comparing the values 

plt.plot(expansion_ratios, isp_values)
plt.xlabel('Expansion Ratio')
plt.ylabel('Specific Impluse (s)')
plt.title('Expansion Ratio vs Specific Impluse')
plt.grid(True)
plt.show()



